New html page structure
john4pius/youtube-video-player-page pull request #5
Opened 2020-06-06 02:03 UTC by john4pius

Hi,
Some changes were made to fix the highlighted issues, please help review the code.

2020-06-06 08:09 UTC, tirthajyoti-ghosh commented
# Pull Request under review by T. Ghosh (TSE)

2020-06-06 08:30 UTC, tirthajyoti-ghosh commented on index.html
> +                        <li><img src="src/notification.png" alt="notifications" style="padding-bottom: 2px;"></li>
### Remove inline styling. All styles should be in the `style.css` file.

2020-06-06 08:31 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Nice work team 🙌

Great job for using semantic tags 👏.

However, there are still some changes you need to work on.

- 👏 for bringing the `Sidebar recommended video` section beside the `main video player` section, but now the `main video player` is encroaching on the `Sidebar recommended video` section 👇
![Annotation 2020-06-06 135051](https://user-images.githubusercontent.com/57726348/83939727-ccee7c00-a7fc-11ea-85a9-81caaf867fe3.jpg)

- This part still has overlapping texts, as pointed out by the previous reviewer 👇
![Annotation 2020-06-06 135215](https://user-images.githubusercontent.com/57726348/83939757-15a63500-a7fd-11ea-8596-36fc33978275.jpg)

- Like/Dislike buttons are still missing, as pointed out by the previous reviewer

- The share button is missing

I have left some comments below. Be sure to check them.

2020-06-06 08:32 UTC, tirthajyoti-ghosh commented on index.html
> +                        <li><img src="src/notification.png" alt="notifications" style="padding-bottom: 2px;"></li>
### Remove inline styling. All styles should be in `style.css` file.

2020-06-06 08:36 UTC, tirthajyoti-ghosh reviewed
[OPTIONAL] Use `<nav>` tag for navigation 

*I noticed you have closed the PR from the first review (#2 ). It is not a good practice to have different PRs for different reviews. You should use the same PR for all reviews.*

Apply the changes and request for another review.
Happy coding👨‍💻

2020-06-07 03:46 UTC, john4pius commented
> [OPTIONAL] Use `<nav>` tag for navigation
> 
> _I noticed you have closed the PR from the first review (#2 ). It is not a good practice to have different PRs for different reviews. You should use the same PR for all reviews._
> 
> Apply the changes and request for another review.
> Happy coding

I unintentionally commit a pull request on review (#2 ) so I had to revert and close it. I will work on your comment and request another review.

2020-06-07 21:10 UTC, elmejdki commented
## Pull Request under review by _Zakariae El Mejdki_.

2020-06-07 22:28 UTC, elmejdki requested changes
# Good job so far team :tophat:, but I :thinking: **Think** you could do too much better
### status: Changes required.

I see that your website is not made for low screen resolution laptops:
<img src="https://user-images.githubusercontent.com/34653764/83981438-b0923280-a915-11ea-870c-ea725e3b0f36.png" width="400" />
I suppose that you have a big screen may be a 4k you should take on consideration that most people have a screen of 1024x768, so try to adapt your page to these screens first then go to bigger ones if you zoom in at least to 150% you will see what I'm trying to say. so next time don't forget to do that, please.

### you are almost there guys please fix the comments bellow then request a new code review.
_if you need anything contact me on slack you, you will find me as **Zakariae El Mejdki**_

2020-06-07 22:28 UTC, elmejdki commented on README.md
> +* Ahmed (https://github.com/Ahmed-Benj)
**[OPTIONAL]** type your full name and also add your Linkedin and twitter profile links.

2020-06-07 22:28 UTC, elmejdki commented on index.html
> +    <!-- The flexible grid (content) -->
please remove all comments from you HTML and CSS files

2020-06-07 22:28 UTC, elmejdki commented on style.css
> +*/
remove all the comments from your CSS file.

2020-06-07 22:28 UTC, elmejdki commented on README.md
> +* Ahmed (https://github.com/Ahmed-Benj)
**[OPTIONAL]** put your full name there, and also add your Linkedin and twitter profile links.

2020-06-07 22:28 UTC, elmejdki commented on index.html
> +    <!-- The flexible grid (content) -->
Please remove all the comments from your HTML and CSS files.
![image](https://user-images.githubusercontent.com/34653764/83981120-0ca78780-a913-11ea-820e-ad382c1b36f5.png)

2020-06-07 22:28 UTC, elmejdki commented on style.css
> +/* Style the body */
don't forget about the comments here also, please.

2020-06-07 22:28 UTC, elmejdki commented on index.html
> +                        <li><img id="post" src="src/video_post.png" alt="create video or post"></li>
**[OTPIONAL]** put the images inside a link tag. cause obviously they are links

2020-06-07 22:28 UTC, elmejdki commented on index.html
> +<html>
please return back the lang attribute it's necessary for screen readers.

2020-06-08 04:00 UTC, john4pius commented
@elmejdki,
we will work on your recommendation.

2020-06-09 00:33 UTC, voscarmv requested changes
# Excellent work on your code team 👍 
## Unfortunately, I have to tag your project as invalid! 🚫 😕 
- Your project presents the following problem when trying to merge this Pull Request:
![image](https://user-images.githubusercontent.com/2739245/84092715-d70ba880-a9bd-11ea-8afd-0b48f29802a8.png)
- Please make proper use use of the Github Flow or Git Flow as requested [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66250306/) and [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)
- Friendly reminder: You should use Github/Git Flow in this project. Please take a step back and watch video [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/). Then create a brand new repo with correct setup and feature branch (with DESCRIPTIVE name) and copy your code there or close this pull request and create another one with correct feature branch . This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!
- Also, please write a more descriptive Pull Request description, as requested [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
![image](https://user-images.githubusercontent.com/2739245/84093088-daebfa80-a9be-11ea-808e-824b57ecb9dc.png)

### Fix these issues and then request another code review!
### Comments or questions? Contact me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻 🗨️ 🧑‍💻 
## Happy Hacking! 🧠 ⌨️ 🖱️ 💻

2020-06-09 06:49 UTC, closed without merging